GET http://localhost:8081/api/user


##


###
POST http://localhost:8081/api/user
Content-Type: application/json

{
  "nameUz" : "Ilhom",
  "nameEn": "Ilhom",
  "nameLt": "Aziz",
  "nameRu" : "Азиз",
  "count" : 1,
  "date" : "30-08-2023"
}

###


DELETE http://localhost:8081/api/user/3



###

PUT http://localhost:8081/api/user/2
Content-Type: application/json

{
  "nameUz" : "Toshkent",
  "nameEn": "Tashkent",
  "nameLt": "Tashkent",
  "nameRu" : "Ташкент",
  "count" : 1,
  "date" : "19-07-2023"
}