GET http://localhost:8081/api/user


##


###
POST http://localhost:8081/api/user
Content-Type: application/json

{
  "nameUz" : "Jackie Chan",
  "nameEn": "Jackie Chan",
  "nameLt": "Jackie Chan",
  "nameRu" : "Jackie Chan",
  "count" : 6,
  "date" : "15-05-2015"
}

###


DELETE http://localhost:8081/api/user/3



###

PUT http://localhost:8081/api/user/2
Content-Type: application/json

{
  "nameUz" : "Toshkent",
  "nameEn": "Tashkent",
  "nameLt": "Tashkent",
  "nameRu" : "Ташкент",
  "count" : 1,
  "date" : "19-07-2023"
}